# This configuration is designed for the nRF52840 Dongle from
# Nordic Semiconductor. It requires the dongle to have the
# SoftDevice 7.3.0 firmware flashed to it. If the device does not have
# SoftDevice 7.3.0 on it, the firmware can be downloaded from
# Nordic Semiconductor and flashed with any compatible tool, such as
# the graphical Programmer tool installabe through nRFConnect.
#
# The nrfutil used by PlatformIO is not able to talk to the Open Bootloader
# that comes with the nRF52840 Dongle by default. The configuration is set
# up with jlink as the uploader, and it is recommended to use the
# shell script upload.sh provided in this directory to flash the device.
#
# There is presently no signature key. If resources allow, future work
# should allow for a signature key and improve integration with PlatformIO.
[uwl_cpe_2025_base]
extends = nrf52_base
board = nrf52840_dongle
board_build.ldscript = boards/nrf52840_dongle.ld
build_flags = ${nrf52_base.build_flags}
  -I variants/pca10059
  -I src/helpers/nrf52
  -I src/helpers/ui
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52
  -D UWL_COMPANION
  -D QSPIFLASH

  -D CONFIG_NFCT_PINS_AS_GPIOS

  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D P_LORA_SCLK=20
  -D P_LORA_MISO=15
  -D P_LORA_MOSI=17
  -D P_LORA_DIO_1=10
  -D P_LORA_NSS=24
  -D P_LORA_RESET=22
  -D P_LORA_BUSY=32
  -D SX126X_RXEN=13
  -D SX126X_TXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D P_LORA_TX_LED=PIN_LED1

  -D PIN_USER_BTN=38
  -D PIN_STATUS_LED=PIN_LED1
  -D DISPLAY_CLASS=ST7789LCDDisplay
  -D USE_PIN_TFT
  -D PIN_TFT_RST=2
  -D PIN_TFT_LEDA_CTL=-1
  -D PIN_TFT_CS=45
  -D PIN_TFT_DC=42
  -D PIN_TFT_SCL=33
  -D PIN_TFT_SDA=47
  -D DISPLAY_SCALE_X=1.875f
  -D DISPLAY_SCALE_Y=5.0f
  -D DISPLAY_ROTATION=1

  -D BLE_PIN_CODE=123456
  -D MAX_CONTACTS=20
lib_deps =
  ${nrf52_base.lib_deps}
  stevemarple/MicroNMEA @ ^2.0.6
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit GFX Library @ ^1.12.5
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  zinggjm/GxEPD2 @ 1.6.2
  bakercp/CRC32 @ ^2.0.0
build_src_filter =
  ${nrf52_base.build_src_filter}
  +<helpers/*.cpp>
  +<TechoBoard.cpp>
  +<helpers/sensors/EnvironmentSensorManager.cpp>
  +<helpers/ui/ST7789LCDDisplay.cpp>
  +<../variants/pca10059>

[env:uwl_capstone]
extends = uwl_cpe_2025_base
board_upload.maximum_size = 712704
build_flags =
  ${uwl_cpe_2025_base.build_flags}
  -I examples/uwl_companion/ui-new
  -D MAX_GROUP_CHANNELS=40
build_src_filter =
  ${uwl_cpe_2025_base.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/uwl_companion/*.cpp>
  +<../examples/uwl_companion/ui-new/*.cpp>
lib_deps =
  ${uwl_cpe_2025_base.lib_deps}
  densaugeo/base64 @ ~1.4.0
platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0
upload_protocol =
  custom
extra_scripts =
  variants/pca10059/upload.py
