# This configuration is designed for the nRF52840 Dongle from
# Nordic Semiconductor with the Open USB bootloader.
#
# This environment requires the device to have SoftDevice 7.3.0 firmware
# flashed to it. If the device does not have SoftDevice 7.3.0 on it,
# the firmware can be downloaded from Nordic Semiconductor and flashed with
# any compatible tool, such as the graphical Programmer tool which is part
# of nRFConnect.
#
# Additionally, this environment requires that the InternalFS in the Adafruit
# framework be moved to an address region that does not conflict with the
# bootloader, which begins at 0xE0000.
#
# The nrfutil used by PlatformIO is not able to talk to the Open Bootloader
# that comes with the nRF52840 Dongle by default. This environment requires
# nrfutil from Nordic Semiconductor.
#
# There is presently no signature key. If resources allow, future work
# should allow for a signature key and improve integration with PlatformIO.


[uwl_cpe_2025_base]
extends = nrf52_base
board = nrf52840_dongle
board_build.ldscript = boards/nrf52840_dongle.ld
build_flags = ${nrf52_base.build_flags}
  -I variants/uwl_capstone
  -I src/helpers/nrf52
  -I src/helpers/ui
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52

  -D UWL_COMPANION
  -D QSPIFLASH
  -D CONFIG_NFCT_PINS_AS_GPIOS

# These defaults override the ones in the Arduino base. For some reason,
# a handful of our boards do not send/receive on any settings if they
# are first initialized with the defaults in the Arduino base. It would
# be good to investigate this if time allows, but we are in the US
# anyway, so it makes sense to use the recommended US defaults.
  -D LORA_FREQ=910.525
  -D LORA_BW=62.5
  -D LORA_SF=7

  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D P_LORA_SCLK=20
  -D P_LORA_MISO=15
  -D P_LORA_MOSI=17
  -D P_LORA_DIO_1=10
  -D P_LORA_NSS=24
  -D P_LORA_RESET=22
  -D P_LORA_BUSY=32
  -D SX126X_RXEN=13
  -D SX126X_TXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1

lib_deps =
  ${nrf52_base.lib_deps}
  adafruit/Adafruit GFX Library @ ^1.12.5
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0

build_src_filter =
  ${nrf52_base.build_src_filter}
  +<../variants/uwl_capstone/*.cpp>
  +<helpers/*.cpp>
  +<helpers/sensors/EnvironmentSensorManager.cpp>
  +<helpers/ui/ST7789LCDDisplay.cpp>

[env:uwl_capstone]
extends = uwl_cpe_2025_base
board_upload.maximum_size = 712704
build_flags =
  ${uwl_cpe_2025_base.build_flags}
  -I examples/companion_radio/ui-new

# The display uses the default SPI peripheral.
  -D PIN_STATUS_LED=PIN_LED1
  -D DISPLAY_CLASS=ST7789LCDDisplay
  -D PIN_TFT_RST=43
  -D PIN_TFT_LEDA_CTL=-1
  -D PIN_TFT_CS=39
  -D PIN_TFT_DC=36
  -D DISPLAY_SCALE_X=1.875f
  -D DISPLAY_SCALE_Y=5.0f
  -D DISPLAY_ROTATION=1

  -D PIN_USER_BTN=38

  -D MAX_CONTACTS=20
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D LORA_TX_POWER=22

build_src_filter =
  ${uwl_cpe_2025_base.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>

lib_deps =
  ${uwl_cpe_2025_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0

upload_protocol =
  custom

extra_scripts =
  variants/uwl_capstone/upload.py
